### PR TITLE
Test building from a PR

### PR DESCRIPTION
**Pull request by humitos**

### CODE REVIEW

**Comment by humitos** [comment]
Did it work? :heart_eyes:

**Comment by humitos** [comment]
I enabled the feature flag on this project and the build was triggered: https://readthedocs.org/projects/test-builds/builds/9417042/ :tada:

**Comment by humitos** [comment]
Wow! https://test-builds.readthedocs.io/en/3/

**Comment by humitos** [comment]
Reopening after adding the RemoteRepository to the Project.

**Comment by humitos** [comment]
Again!

**Comment by humitos** [comment]
Closing the PR should delete the online docs?

**Comment by humitos** [comment]
Yes! Wow! Amazing!

**Comment by saadmk11** [comment]
> Closing the PR should delete the online docs?

Yes

**Comment by ericholscher** [comment]
I'm -1 on deleting the docs.

**Comment by humitos** [comment]
Let's move this to another place. I'm interested in knowing why. I feel like deleting the docs is the right approach, but seems you have some good points.

**Pull request closed without merging**
