### PR TITLE
Add MkDocs test build with python/name tags in mkdocs.yml

### PR DESCRIPTION
**Pull request by humitos**

### CODE REVIEW

**Comment by humitos** [comment]
@pawamoy I think you may need to add a `readthedocs.yaml` file to tell RTD to use MkDocs for the build.

**Comment by pawamoy** [comment]
Alright, it's correctly failing as expected :slightly_smiling_face:

**Comment by humitos** [comment]
Good! I'm merging this so I can easily test it locally. Looks fine, anyways. We can adapt as we go, otherwise.

**Comment by humitos** [comment]
Excellent! It worked. I only had to upgrade MkDocs to its latest version!

Screenshot_2020-09-29_17-17-37

Thanks you a lot for your help on this!

**Pull request merged**
